{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "95773486_8959ee29",
        "filename": "src/HwmonTempSensor.cpp",
        "patchSetId": 4
      },
      "lineNbr": 66,
      "author": {
        "id": 1001286
      },
      "writtenOn": "2022-01-16T12:56:21Z",
      "side": 1,
      "message": "This also have same zombie object problem as I mentioned in TachSensor class. If it\u0027s applicable please make necessary changes in all the places.",
      "range": {
        "startLine": 64,
        "startChar": 0,
        "endLine": 66,
        "endChar": 40
      },
      "revId": "328732136524fbb7551a1bf7f8c76bbb8566ef14",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "54b36cce_e120a206",
        "filename": "src/TachSensor.cpp",
        "patchSetId": 4
      },
      "lineNbr": 64,
      "author": {
        "id": 1001286
      },
      "writtenOn": "2022-01-16T12:56:21Z",
      "side": 1,
      "message": "From caller\u0027s point of view(one who is creating object), Object creation succeeds even if file open call fails. Caller\u0027s execution will keep going forward in same direction as if open was successful(even if it fails) only to fail at some later stage. If my understanding here is correct then I think it\u0027s better to throw exception rather than silently returning leaving object in zombie state.\nhttps://isocpp.org/wiki/faq/exceptions#ctors-can-throw",
      "range": {
        "startLine": 63,
        "startChar": 0,
        "endLine": 64,
        "endChar": 15
      },
      "revId": "328732136524fbb7551a1bf7f8c76bbb8566ef14",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4e385054_6f7ce13e",
        "filename": "src/TachSensor.cpp",
        "patchSetId": 4
      },
      "lineNbr": 66,
      "author": {
        "id": 1000163
      },
      "writtenOn": "2022-01-14T22:27:17Z",
      "side": 1,
      "message": "I was trying to figure out if these two are equivalent. I guess the original just silently fails, while this one has a cerr message.",
      "range": {
        "startLine": 58,
        "startChar": 0,
        "endLine": 66,
        "endChar": 24
      },
      "revId": "328732136524fbb7551a1bf7f8c76bbb8566ef14",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5f457e48_c505b652",
        "filename": "src/TachSensor.cpp",
        "patchSetId": 4
      },
      "lineNbr": 66,
      "author": {
        "id": 1000153
      },
      "writtenOn": "2022-01-15T23:34:47Z",
      "side": 1,
      "message": "Correct, this one is arguably better, so we at least log failures, instead of throwing an exception in a constructor, which is less-than-defined behavior.",
      "parentUuid": "4e385054_6f7ce13e",
      "range": {
        "startLine": 58,
        "startChar": 0,
        "endLine": 66,
        "endChar": 24
      },
      "revId": "328732136524fbb7551a1bf7f8c76bbb8566ef14",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}